###

GET http://localhost:5000/users




###

POST http://localhost:5000/users/
Content-Type: application/json

{
    "email": "johndoe1@gmail.com",
    "password": "john123",
    "name": "John Doe"
}